### ISSUE TITLE
Add recent changes to repo, and create recipe for installation

### ISSUE THREAD

**Issue by agstephens** [cedadev/esgf-stac-client#1]
Hi @rhysrevans3, please can you quickly run through the test instructions here:

https://github.com/cedadev/esgf-stac-client/blob/master/README.md

Check that they work for you okay. If so, then we can safely hand them to @Adik8688

**Comment by rhysrevans3** [comment]
Yes this worked for me. Only note I would make is if you're doing it locally you don't need the `GITHUB_ID:GITHUB_ACCESS_TOKEN` and can just use ssh.

**Comment by agstephens** [comment]
Thanks @rhysrevans3: good point about github.

@Adik8688: how do you authenticate to github normally? Do you use an access token or and SSH key?

**Comment by agstephens** [comment]
Done, in README.md.
